apiVersion: v1
kind: Service
metadata:
  name: docuvault-client
  namespace: docuvault

spec:
  selector:
    app: docuvault-client

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: LoadBalancer