apiVersion: v1
kind: Service
metadata:
  name: docuvault-server
  namespace: docuvault

spec:
  selector:
    app: docuvault-server

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

  type: ClusterIP