import axios from 'axios'
import { mockDocuments } from '@/data/mockData'

/* ------------------------------------------------------------------
 * Configuration
 * ------------------------------------------------------------------ */

const API_URL = import.meta.env.VITE_API_URL
export const MAX_UPLOAD_MB = Number(import.meta.env.VITE_MAX_UPLOAD_MB || 25)

// Use mock data when explicitly requested or when no API URL is configured.
export const USE_MOCK =
  import.meta.env.VITE_USE_MOCK === 'true' || !API_URL

export const MAX_UPLOAD_BYTES = MAX_UPLOAD_MB * 1024 * 1024
export const ALLOWED_EXTENSIONS = ['pdf', 'docx', 'txt', 'png', 'jpg', 'jpeg']

/* ------------------------------------------------------------------
 * Axios instance
 * ------------------------------------------------------------------ */

const client = axios.create({
  baseURL: API_URL,
  timeout: 20000,
  headers: { 'Content-Type': 'application/json' },
})

// Clerk issues short-lived session tokens. Components register a getter
// (see AppLayout) so every request carries a fresh bearer token — the
// frontend never stores tokens itself.
let tokenGetter = null
export function registerTokenProvider(fn) {
  tokenGetter = fn
}

client.interceptors.request.use(async (config) => {
  if (tokenGetter) {
    const token = await tokenGetter()
    if (token) config.headers.Authorization = `Bearer ${token}`
  }
  return config
})

client.interceptors.response.use(
  (res) => res,
  (error) => {
    const message =
      error.response?.data?.message ||
      error.message ||
      'Something went wrong. Please try again.'
    return Promise.reject(new Error(message))
  },
)

/* ------------------------------------------------------------------
 * Mock helpers — an in-memory store so the demo feels real
 * (uploads, renames and deletes persist for the session).
 * ------------------------------------------------------------------ */

const delay = (ms) => new Promise((r) => setTimeout(r, ms))
const clone = (v) => JSON.parse(JSON.stringify(v))

let store = clone(mockDocuments)

function nowIso() {
  return new Date().toISOString()
}

function buildMockInsights(doc) {
  return {
    summary:
      doc.summary ||
      `This ${doc.type.toUpperCase()} document has been analyzed. It covers its core subject in ${doc.pages || 'several'} pages, with the key themes surfaced below.`,
    keywords: doc.keywords?.length ? doc.keywords : ['Document', 'Analysis', 'Cloud'],
    classification: doc.classification || { label: 'General Document', confidence: 0.8 },
  }
}

function mockAnswer(doc, question) {
  const kw = doc.keywords?.slice(0, 3).join(', ') || 'the core topics'
  return `Based on "${doc.name}", ${question.trim().replace(/\?+$/, '')} — the document focuses on ${kw}. ${
    doc.summary ? doc.summary.split('. ')[0] + '.' : 'A detailed answer would draw on the full extracted text.'
  } (This response is generated by the mock AI service and will be powered by Amazon Bedrock once the backend is connected.)`
}

/* ------------------------------------------------------------------
 * API methods
 * Each method uses mock data today; the commented block shows the real
 * call so switching to the backend is a one-line change.
 * ------------------------------------------------------------------ */

export const api = {
  /** List documents. */
  async getDocuments() {
    if (USE_MOCK) {
      await delay(650)
      return clone(store)
    }
    const { data } = await client.get('/documents')
    return data
  },

  /** Fetch a single document by id. */
  async getDocument(id) {
    if (USE_MOCK) {
      await delay(450)
      const doc = store.find((d) => d.id === id)
      if (!doc) throw new Error('Document not found.')
      return clone(doc)
    }
    const { data } = await client.get(`/documents/${id}`)
    return data
  },

  /**
   * Upload a document.
   *
   * Real AWS flow (two steps, no credentials in the browser):
   *   1) POST /documents/upload-url  -> backend returns a pre-signed S3 URL
   *   2) PUT the file directly to that URL (private S3 bucket)
   *
   * @param {File} file
   * @param {{ onProgress?: (percent:number)=>void, signal?: AbortSignal }} options
   */
  async uploadDocument(file, { onProgress, signal } = {}) {
    if (USE_MOCK) {
      await new Promise((resolve, reject) => {
        let percent = 0
        const tick = setInterval(() => {
          if (signal?.aborted) {
            clearInterval(tick)
            reject(new DOMException('Upload cancelled', 'AbortError'))
            return
          }
          percent = Math.min(100, percent + Math.random() * 18 + 6)
          onProgress?.(Math.round(percent))
          if (percent >= 100) {
            clearInterval(tick)
            resolve()
          }
        }, 260)
      })
      const ext = file.name.split('.').pop().toLowerCase()
      const newDoc = {
        id: `doc-${Date.now()}`,
        name: file.name,
        type: ext === 'jpeg' ? 'jpg' : ext,
        size: file.size,
        uploadedAt: nowIso(),
        modifiedAt: nowIso(),
        owner: 'You',
        status: 'processing',
        favorite: false,
        pages: null,
        summary: null,
        keywords: [],
        classification: null,
        activity: [{ type: 'upload', label: 'Document uploaded', at: nowIso() }],
      }
      store = [newDoc, ...store]
      return clone(newDoc)
    }

    // --- Real backend ---
    const { data: presigned } = await client.post('/documents/upload-url', {
      fileName: file.name,
      contentType: file.type,
      size: file.size,
    })
    await axios.put(presigned.uploadUrl, file, {
      headers: { 'Content-Type': file.type },
      signal,
      onUploadProgress: (e) => {
        if (onProgress && e.total) onProgress(Math.round((e.loaded / e.total) * 100))
      },
    })
    const { data } = await client.post('/documents', { documentId: presigned.documentId })
    return data
  },

  /** Delete a document. */
  async deleteDocument(id) {
    if (USE_MOCK) {
      await delay(500)
      store = store.filter((d) => d.id !== id)
      return { success: true }
    }
    const { data } = await client.delete(`/documents/${id}`)
    return data
  },

  /** Rename a document. */
  async renameDocument(id, name) {
    if (USE_MOCK) {
      await delay(450)
      store = store.map((d) =>
        d.id === id ? { ...d, name, modifiedAt: nowIso() } : d,
      )
      return clone(store.find((d) => d.id === id))
    }
    const { data } = await client.patch(`/documents/${id}`, { name })
    return data
  },

  /** Toggle favorite state. */
  async toggleFavorite(id, favorite) {
    if (USE_MOCK) {
      await delay(200)
      store = store.map((d) => (d.id === id ? { ...d, favorite } : d))
      return clone(store.find((d) => d.id === id))
    }
    const { data } = await client.patch(`/documents/${id}`, { favorite })
    return data
  },

  /** Get (or trigger) the AI summary, keywords and classification. */
  async getAISummary(id) {
    if (USE_MOCK) {
      await delay(900)
      const doc = store.find((d) => d.id === id)
      if (!doc) throw new Error('Document not found.')
      return buildMockInsights(doc)
    }
    const { data } = await client.get(`/documents/${id}/insights`)
    return data
  },

  /** Ask a natural-language question about a document. */
  async askAI(id, question) {
    if (USE_MOCK) {
      await delay(1100)
      const doc = store.find((d) => d.id === id)
      if (!doc) throw new Error('Document not found.')
      return { answer: mockAnswer(doc, question) }
    }
    const { data } = await client.post(`/documents/${id}/ask`, { question })
    return data
  },

  /** Aggregate stats for the dashboard. */
  async getStats() {
    if (USE_MOCK) {
      await delay(500)
      return computeStats(store)
    }
    const { data } = await client.get('/stats')
    return data
  },
}

/** Derive dashboard stats from a list of documents. */
export function computeStats(docs) {
  const totalBytes = docs.reduce((sum, d) => sum + (d.size || 0), 0)
  return {
    totalDocuments: docs.length,
    storageBytes: totalBytes,
    aiProcessed: docs.filter((d) => d.status === 'completed').length,
    processing: docs.filter((d) => d.status === 'processing').length,
  }
}

export default api
